### ISSUE TITLE
Payment Methods Enabled By Default

### ISSUE THREAD

**Issue by sprankhub** [wirecard/magento-wcs#14]
When installing this extension, nearly all new payment methods are enabled by default. This does not make any sense as you have to configure them first. All new payment methods should be disabled by default.

**Comment by jakubpolomsky** [comment]
Thank you for your input. This will be fixed in the next release. Enabled payment methods by default are going to be: 
1. MasterPass
2. Credit card
3. Sofort Banking
4. Invoice
5. SEPA Direct Debit
6. PayPal

**Comment by sprankhub** [comment]
I think no payment method should be enabled by default. You first have to set your user ID, keys etc., so that these methods work. Hence, no method should be enabled initially.

**Comment by jakubpolomsky** [comment]
The default config should be demo. Therefore you can test the plugin straight after installing without configuring anything. That's how it's done with every plugin from us. The amount of payment methods sure is quite big so I reduced the number of initially enabled ones. Should this be considered obsolete, I shall let you know about an update next monday after we discuss this with our product management. Until then I'll leave the settings like I set them in the last commit. [530485b](https://github.com/wirecard/magento-wcs/commit/530485bec17a4db6ff7e44e93acba2a13b1f2e74)

**Comment by sprankhub** [comment]
The issue is that if you deploy this to live on a highly frequented shop, people will see and use the new payment methods with the demo data. This may not happen in any case! From a technical point of view, this is a no-go! I really hope the product management understands this.

**Comment by jakubpolomsky** [comment]
Thank you once again for letting us know. We have decided to disable all payment methods by default. Have a nice day!
