### ISSUE TITLE
Usage of $j Fails If rwd Theme Not Used

### ISSUE THREAD

**Issue by sprankhub** [wirecard/magento-wcs#17]
Under https://github.com/wirecard/magento-wcs/blob/master/js/wirecard/checkoutseamless/processing.js, you use `$j`, which is supposed to be a reference to jQuery. But it is only defined if one uses the rwd theme or a child theme thereof. If you have a custom theme, which is not built on top of rwd/default, then `$j` is not available. Hence, the checkout breaks.

You should replace the usage of `$j` with basic `$` / prototype.

**Comment by rinnhofer** [comment]
Thank you for your contribution, we will look into it as soon as possible and inform you when we finish a solution for issue #15 too.

Kind regards
