### ISSUE TITLE
Fatal error: Cannot unset $this in  .. app/code/local/WirecardCEE/Stdlib/Client/ClientAbstract.php on line 300

### ISSUE THREAD

**Issue by mvenghaus** [wirecard/magento-wcs#23]
Why?

    /**
     * Destructor
     */
    public function __destruct()
    {
        unset( $this );
    }

**Comment by jakubpolomsky** [comment]
This is a php 7.1 issue, we will address this in the next release. What you can do is to upgrade the client library to the newest version or revert your php to 7.0

**Comment by mvenghaus** [comment]
thx for the fast reply. For my understanding .. isn't unset the same destruct does ?

**Comment by jakubpolomsky** [comment]
You are welcome. And that assumption is not correct. The destructor is being called when an object is being deleted (destroyed) the unset is a method deleting (destroying) an object - thus calling a possible destructor.
